import type { Metadata } from "next";

import ProtectAdminRoute from "@/providers/ProtectAdmin";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ProtectAdminRoute>{children}</ProtectAdminRoute>;
}
