import type { Metadata } from "next";
import ProtectGestRoute from "@/providers/ProtectGest";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ProtectGestRoute>{children}</ProtectGestRoute>;
}
