import type { Metadata } from "next";

import AuthProvider from "@/providers/AuthContext";

import ProtectUserRoute from "@/providers/ProtectUser";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ProtectUserRoute>{children}</ProtectUserRoute>;
}
