import type { Metadata } from "next";

import { RoleProtectedRoute } from "@/providers/RouteValidation";
import AuthProvider from "@/providers/AuthContext";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <RoleProtectedRoute requiredRoles={["user"]} children={children} />
    </AuthProvider>
  );
}
